### ISSUE TITLE
[suggestion] Props handling

### ISSUE THREAD

**Issue by ale1313** [villagoizi/rn-challenge-rick-and-morty#2]
It is better, at least in this specific case, to send the component props separately, as the syntax is more clear to understand and above all gives the code a cleaner look.

https://github.com/villagoizi/rn-challenge-rick-and-morty/blob/f3bc858981242b6976201cd6420498ec57d50222/src/components/Header.tsx#L32

**Comment by villagoizi** [comment]
Yes, it is ok for this case. I remove it because I was adding functionality that I don't use. I did refactoring of this part.
