### ISSUE TITLE
[minor] Missing argument types

### ISSUE THREAD

**Issue by ale1313** [villagoizi/rn-challenge-rick-and-morty#7]
https://github.com/villagoizi/rn-challenge-rick-and-morty/blob/f3bc858981242b6976201cd6420498ec57d50222/src/screen/Characters/CharactersScreen.tsx#L63

**Comment by villagoizi** [comment]
keyExtractor has inferred the type! If I add type in this case, I'm adding type unnecesarily. But i.toString() is not correct, is a bad practice. It is resolved
