### ISSUE TITLE
[minor] Avoid "over-typing" your variables

### ISSUE THREAD

**Issue by ale1313** [villagoizi/rn-challenge-rick-and-morty#8]
I noticed that you typed some variables more times than you need to. I believe this is due to lack of a linting tool (maybe using TSLint would help you to avoid this)

**Comment by villagoizi** [comment]
Can you show me where? Pls.

**Comment by ale1313** [comment]
For example this line, which I referenced in another issue, was an example of over-typing. You have examples like this in various part of your program.
https://github.com/villagoizi/rn-challenge-rick-and-morty/blob/f3bc858981242b6976201cd6420498ec57d50222/src/components/Header.tsx#L36
