### ISSUE TITLE
[minor, suggestion] Return block full of conditions

### ISSUE THREAD

**Issue by ale1313** [villagoizi/rn-challenge-rick-and-morty#9]
In this specific return, you have multiple conditions setting what should be render and what not. This isn't exactly a clean code, and I can suggest you doing another render method, perhaps using a render function, to handle in a more clear way each condition you need to verify. Sometimes, using if blocks can help your code be cleaner.

https://github.com/villagoizi/rn-challenge-rick-and-morty/blob/f3bc858981242b6976201cd6420498ec57d50222/src/screen/Characters/CharactersScreen.tsx#L47

**Comment by villagoizi** [comment]
I did create an handleQuery that it wrap the screens Character, Location and Episodes. Now it has a look cleaner
